### ISSUE TITLE
朴素算法一，没太看懂，帮忙解释下吧

### ISSUE THREAD

**Issue by guagua777** [hczhcz/opparser#1]
设变量x=1；
从当前位置开始查找括号；
如果遇到左括号，x=x+1；
如果遇到右括号，x=x-1；
当x=0时，找到匹配的右括号。

为什么初始值是1？
               （  （   ） ）
初始值1， 2    3  2   1

**Comment by hczhcz** [comment]
这里写得不太清楚，应该是“当遇到一个左括号时，从左括号右侧开始向右查找”
```
( ( ) )
 ^ 从这里开始，x=1
   ^ x=2
     ^ x=1
       ^ x=0，找到了，结束
```

**Comment by guagua777** [comment]
谢谢

**Comment by guagua777** [comment]
但是，目前我们并不能容易地标出这种层次编号，于是我们需要进行一些构造：

把所有数字用括号围住。
改变“提升”方式，让某些运算符的编号“对齐”（关于某数同余）。
1 (1)+((2)+(3))*(4)+(5)
2  3 1  6 4 6  2 3 1 3
3 
4 1+(2+3)*4+5
5 31 646 2313
然后我们就得到标注方法：

从3开始；
遇到数字，输出当前层次的数字；
遇到加号，输出当前层次减二的加号；
遇到乘号，输出当前层次减一的乘号；
遇到左括号，层次加3；
遇到右括号，层次减3。

这块没太看懂，有没有通俗点的文章，推荐下？

**Comment by hczhcz** [comment]
自行推导
或者看下方的伪代码
